return PlaceObj('ModDef', {
    'title', "Mouse Cursor Consoles",
    'id', "MouseCursorConsoles",
    'author', "fredware",
    'short_description', "TEST BUILD - NOT READY. Toggle a left-stick mouse cursor with R3; hold L2/LT for faster movement. PS5 and Xbox Series testing required.",
    'image', "Mod/MouseCursorConsoles/Images/test-not-ready.png",
    'version', 4,
    'lua_revision', 350453,
    'saved_with_revision', 405907,
    'description', "Toggle a left-stick mouse cursor with R3 / right-stick click from the main menu (Tutorial, New Game, Load Game), setup screens, or gameplay. Mouse mode stays on between screens. Hold L2 / LT for faster movement (default 2.5x). Configure speeds, size, response, smoothing and bindings in Options > Controls > Mouse Cursor Consoles. Cross / A: left click; Circle / B: right click; L1 / LB: wheel up; R1 / RB: wheel down; Options / Menu: Escape. R3 is reserved for the toggle while this mod is enabled. Uses a temporary PC interface and restores previous controls when switched off. PS5 and Xbox Series X|S runtime testing is still required; this release is not console-certified.",
    'last_changes', "Added Mouse Cursor Consoles at the top of Options > Controls. Fixed missing metadata defaults that hid the native Mod Options category. Existing cursor behavior and saved preferences are preserved.",
    'default_options', {
        CURSOR_SPEED = 900, CURSOR_FAST_SPEED = 2250, CURSOR_SIZE = 100,
        STICK_DEADZONE = 6000, RESPONSE_CURVE = "Linear", SMOOTHING_MS = 0,
        CURSOR_COLOR = "White", REMEMBER_POSITION = true,
        TOGGLE_BUTTON = "RightThumbClick", SPEED_BOOST_BUTTON = "LeftTrigger",
        LEFT_CLICK_BUTTON = "ButtonA", RIGHT_CLICK_BUTTON = "ButtonB",
        WHEEL_UP_BUTTON = "LeftShoulder", WHEEL_DOWN_BUTTON = "RightShoulder",
        MENU_BUTTON = "Start",
    },
    'code', {
        "Code/mcc_config.lua",
        "Code/mcc_debug.lua",
        "Code/mcc_settings.lua",
        "Code/mcc_cursor.lua",
        "Code/mcc_input.lua",
        "Code/mcc_lifecycle.lua",
        "Code/mcc_settings_ui.lua",
        "Code/MouseCursorConsoles.lua",
    },
    'TagInterface', true,
})
